# Site
name: "James Hu"
# description: "Jekyll Template for Blogging"
# meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# url: https://ljameshu.github.io
# baseurl: /LJamesHuSite
google_analytics: 'UA-55715114-1'
disqus: 'ljameshu'
# mailchimp-list:

permalink: /:year/:month/:day/:title:output_ext

# Authors
authors:
  james:
    name: James
    display_name: James
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: contact@LJamesHu.com
    web: https://LJamesHu.com
    # twitter: https://twitter.com/wowthemesnet
    # description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'

# # Pagination
# paginate: 6
# paginate_path: /page:num/

pagination:
  enabled: true
  sort_field: 'date'
  sort_reverse: true
  # permalink: '/:num/'
  trail:
    before: 2
    after: 2

# Other
markdown: kramdown
highlighter: rouge
destination: docs
keep_files: ['CNAME']

exclude:
  - .jekyll-cache